language: perl

install:
  - sudo apt-get update
  - sudo apt-get install libarchive-dev
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | grep -v inc::SeeAlso |cpanm -n
  - cpanm -n Exporter::Tidy ExtUtils::CChecker Math::Int64
  - cpanm -n Mojolicious Pod::Abstract
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true
  - cpanm -n ExtUtils::CChecker
  ## workaround for gh#31
  #- cpanm -n http://cpan.metacpan.org/authors/id/R/RJ/RJBS/Mixin-Linewise-0.102.tar.gz

perl:
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

env:
  - ALIEN_LIBARCHIVE=share
  - ALIEN_LIBARCHIVE=system

script:
  - cpanm -n -v Alien::Libarchive
  - dzil test -v

